<!DOCTYPE html>
<html lang="en">

<head>
    <base href="http://localhost/proyectos/tpe/">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@200;500;700&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<?php session_start(); ?>

<body>
    <header class="header">

        <nav class="navbar">
            <a href="">Inicio</a>
            <a href="categorias">Categorias</a>
            <a href="juegos">Juegos</a>
            <?php if (isset($_SESSION['rol']) && $_SESSION['rol'] == 1) {
                echo '<a href="admin">Admin</a>';
            } ?>
            <?php if (isset($_SESSION['name'])) {
                echo '<a href="logout">Logout</a>';

                echo '<h2 class="nameUser">' . $_SESSION['name'] . '</h2>';
            } else {
                echo '<a href="login">Login</a>';
            } ?>



        </nav>
    </header>

</body>

</html>