<?php
require __DIR__ . '../../templates/header.phtml';
?>


<button><a href="/proyectos/tpe/createForm">Nuevo</a></button>
<section>
    <table>
        <tr>
            <th>ID</th>
            <th>Título</th>
            <th>genero</th>
        </tr>

        <?php
        foreach ($juegos as $juego) {
            echo "
           <tr>
                <td>$juego->id</td>
               <td>$juego->nombre</td>
                <td>$juego->genero</td>
                <td><a href='/proyectos/tpe/deleteJuegoConfirm/$juego->id'>Eliminar</a></td>
                <td><a href='/proyectos/tpe/updateForm/$juego->id'>Editar</a></td>
             
           </tr>
       ";
        } ?>
    </table>
</section>