<?php
include './templates/header.phtml';
?>
<div style="text-align: center;">

    </form>
    <h2>Por favor, seleccione una categoria:</p>
    <form action="buscarPorCategoria" method="post">
    <select  id="select" name="categoria"><?php //TRAER LOS GENEROS RECORRIENDO UN ARREGLO QUE LO TRAIGA DE LA BD ?>
    <?php foreach ($categorias as $categoria) : ?>
        <option value=<?=$categoria ?> id=""><?= $categoria ?></option>
    <?php endforeach ?>
    </select>
    <button type="submit">Buscar por categoria</button>

    </form>

</div>


