<?php
//MOSTRAR SI HAY SESSION
?>

<form class="formDesarrollador" action="createDesarrollador" method="post">
    
    <label for="nombreDesarrrollador">Nombre</label>
    <input name="nombreDesarrollador" type="text">
    <label for="sedeDesarrrollador">Sede</label>
    <input name="sedeDesarrollador" type="text">
    <label for="fundacionDesarrrollador">Año de Fundacion</label>
    <input name="fundacionDesarrollador" type="text">
    <label for="propietarioDesarrrollador">Propietario</label>
    <input name="propietarioDesarrollador" type="text">
    <button class="button"><span>Agregar</span></button>
    <p class=passwrong><?php echo $mensaje='';//NO ME TOMA EL COLOR ROJO (VIENE DEL) ?></p>

</form>