<?php
include './templates/header.phtml';
$juegoController = new JuegoController();
$categorias = $juegoController->getCategorias();
?>


<form action="create" method="post">
    <label for="nombreJuego">Nombre</label>
    <input name="nombreJuego" type="text">
    <select id="select" name="genero"><?php //TRAER LOS GENEROS RECORRIENDO UN ARREGLO QUE LO TRAIGA DE LA BD ?>
    <?php foreach ($categorias as $categoria) : ?>
        <option name=<?= $categoria ?> id=""><?= $categoria ?></option>
    <?php endforeach ?>
    </select>
    <label for="año">Año</label>
    <input name="año" type="text">

    <button>Crear</button>
</form>