<?php
//include './templates/header.phtml';

?>



<form action="create" method="post">
    <label for="nombreDesarrrollador">Nombre</label>
    <input name="nombreDesarrollador" type="text">
    <label for="sedeDesarrrollador">Sede</label>
    <input name="sedeDesarrollador" type="text">
    <label for="fundacionDesarrrollador">Año de Fundacion</label>
    <input name="fundacionDesarrollador" type="text">
    <label for="propietarioDesarrrollador">Propietario</label>
    <input name="propietarioDesarrollador" type="text">
    <button>Crear</button>
</form>