<?php
include './templates/header.phtml';
//include './templates/createFormDesarrollador.phtml';
/*  Con esto elimino      <a href="eliminar/<?= $desarrollador->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>    
*/

?>



<table>
    <thead>
        <tr>
            <th>Numero</th>
            <th>Nombre</th>
            <th>Sede</th>
            <th>Año de Fundación</th>
            <th>Propietario</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($desarrolladores as $desarrollador) : ?>

            <tr>
                <td><?= $desarrollador->id ?></td>
                <td><?= $desarrollador->nombre?></td>
                <td><?= $desarrollador->sede ?></td>
                <td><?= $desarrollador->año_fundacion ?></td>
                <td><?= $desarrollador->propietario ?></td>
                <td><button>Editar</button></td>
                <td><button>Eliminar</button></td>


            </tr>
            <tr>
            </tr>


        <?php endforeach ?>

    </tbody>

</table>
<p class=passwrong><?php echo $mensaje='';//NO ME TOMA EL COLOR ROJO (VIENE DEL) ?></p>


<br>
<br>



