<?php
include './templates/header.phtml';

//include './templates/createFormDesarrollador.phtml';
/*  Con esto elimino      <a href="eliminar/<?= $desarrollador->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>    
*/

?>



<table>
    <thead>
        <tr>
            <th>Numero</th>
            <th>Nombre</th>
            <th>Sede</th>
            <th>Año de Fundación</th>
            <th>Propietario</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($desarrolladores as $desarrollador) : ?>

            <tr>
                <td><?= $desarrollador->id ?></td>
                <td><?= $desarrollador->nombre?></td>
                <td><?= $desarrollador->sede ?></td>
                <td><?= $desarrollador->año_fundacion ?></td>
                <td><?= $desarrollador->propietario ?></td>
                <?php if (isset($_SESSION['USER_ID']) && isset($_SESSION['USER_NAME'])) : ?>
                <td>
                    <form action="editarDesarrollador" method="post">
                        <input type="hidden" name="desarrolladorId" value="<?= $desarrollador->id ?>">
                        <button type="submit">Editar</button>
                    </form>
                </td>
                <td>
                    <form action="deleteDesarrollador" method="post">
                        <input type="hidden" name="desarrolladorId" value="<?= $desarrollador->id ?>">
                        <button type="submit">Borrar</button>
                    </form>
                    <?php endif; ?>
                </td> 


            </tr>
        <?php endforeach ?>

    </tbody>

</table>


<br>
<br>



