<?php include __DIR__ . '../../templates/header.phtml';

if (isset($_SESSION['email'])) {
    echo "<h1>Admin view</h1>";
}
?>



<section class="loginSect">


    <form class="form" method="POST" action="/proyectos/tpe/auth">
        <h2>Iniciar sesión</h2>
        <label for="email">Usuario</label>
        <input name="email" type="text">
        <label for="password">Contraseña</label>
        <input name="password" type="password">

        <button class="button">
            <span>
                Enviar
            </span>
        </button>
    </form>
    <img class="loginImage" src="images/img-login.jpg" alt="">

</section>