<?php include './templates/header.phtml';





if (isset($_SESSION['User'])) {
    echo "<h1>Admin view</h1>";
}
?>



<section class="loginSect">


    <form class="form" method="POST" action="auth">
        <h2>Iniciar sesión</h2>
        <label for="user">Usuario</label>
        <input name="user" type="text">
        <label for="password">Contraseña</label>
        <input name="password" type="password">
        <p class=passwrong><?php echo $mensaje; //NO ME TOMA EL COLOR ROJO (VIENE DEL) 
                            ?></p>

        <button class="button">
            <span>
                Enviar
            </span>
        </button>
    </form>
    <img class="loginImage" src="images/img-login.jpg" alt="">

</section>