<?php 
include __DIR__ . '../../templates/header.phtml'; 
$juegoController = new JuegoController();
$categorias = $juegoController->getCategorias();

?>

<form action="updateGame"<?= $juego->id ?> method="post">
    <label for="nombre">Nombre</label>
    <input name="nombre" type="text">
    <select id="select" name="genero"><?php //TRAER LOS GENEROS RECORRIENDO UN ARREGLO QUE LO TRAIGA DE LA BD ?>
    <?php foreach ($categorias as $categoria) : ?>
        <option name=<?= $categoria ?> id=""><?= $categoria ?></option>
    <?php endforeach ?>
    </select>
    <label for="año">Año</label>
    <input value="<?= $juego->año_lanzamiento ?>" name="año" type="text">

    <button>Editar</button>
</form>